
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(QWidget):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(820, 727)
        Form.setStyleSheet(u"background-color: #454d6b")
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(-30, -20, 861, 751))
        self.widget.setStyleSheet(u"background-color: #454d6b")
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(180, 140, 481, 341))
        self.widget_2.setStyleSheet(u"background-color: #373d56")
        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(110, 0, 271, 51))
        font = QFont()
        font.setFamilies([u"Tlwg Typist"])
        self.label.setFont(font)
        self.label.setStyleSheet(u"font-size: 35px")
        self.line = QFrame(self.widget_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(90, 40, 291, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.Sair_botao = QPushButton(self.widget_2)
        self.Sair_botao.setObjectName(u"Sair_botao")
        self.Sair_botao.setGeometry(QRect(300, 290, 90, 28))
        self.Sair_botao.setStyleSheet(u"background-color: #2c3245; color: white; border-radius: 5px; border: none")
        self.voltar_botao = QPushButton(self.widget_2)
        self.voltar_botao.setObjectName(u"voltar_botao")
        self.voltar_botao.setGeometry(QRect(90, 290, 90, 28))
        self.voltar_botao.setStyleSheet(u"background-color: #2c3245; color: white; border-radius: 5px; border: none")
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 160, 221, 20))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"font-size: 15px")
        self.label_3 = QLabel(self.widget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 110, 151, 20))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"font-size: 15px")
        self.line_2 = QFrame(self.widget_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(70, 110, 20, 81))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.widget_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(380, 90, 16, 111))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.widget_2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(80, 90, 311, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.widget_2)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(90, 140, 291, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.widget_2)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(80, 190, 311, 20))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Fale conosco", None))
        self.Sair_botao.setText(QCoreApplication.translate("Form", u"Sair", None))
        self.voltar_botao.setText(QCoreApplication.translate("Form", u"Voltar", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"vieirabrayan42@gmail.com", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Email de suporte", None))
    # retranslateUi
