
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
class Ui_Form(QWidget):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(830, 730)
        self.widget_2 = QWidget(Form)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(-60, 0, 911, 741))
        self.widget_2.setStyleSheet(u"background-color: #454d6b")
        self.Tela_2 = QWidget(self.widget_2)
        self.Tela_2.setObjectName(u"Tela_2")
        self.Tela_2.setGeometry(QRect(240, 120, 481, 431))
        self.Tela_2.setStyleSheet(u"background-color: #373d56")
        self.Usuario_input = QLineEdit(self.Tela_2)
        self.Usuario_input.setObjectName(u"Usuario_input")
        self.Usuario_input.setGeometry(QRect(90, 90, 281, 51))
        self.Usuario_input.setPlaceholderText(u"Insira Seu nome de Usuário ")
        self.Usuario_input.setStyleSheet("padding: 17px")
        self.input_senha = QLineEdit(self.Tela_2)
        self.input_senha.setObjectName(u"input_senha")
        self.input_senha.setStyleSheet("padding: 17px")
        self.input_senha.setGeometry(QRect(90, 160, 281, 51))
        self.Botao_login = QPushButton(self.Tela_2)
        self.Botao_login.setObjectName(u"Botao_login")
        self.Botao_login.setGeometry(QRect(260, 300, 141, 31))
        self.Botao_login.setStyleSheet(u"background-color: #2c3245; color: white; border-radius: 5px; border: none")
        self.Texto_de_login = QLabel(self.Tela_2)
        self.Texto_de_login.setObjectName(u"Texto_de_login")
        self.Texto_de_login.setGeometry(QRect(120, 0, 281, 61))
        font = QFont()
        font.setFamilies([u"Tlwg Typist"])
        font.setPointSize(18)
        font.setItalic(True)
        self.Texto_de_login.setFont(font)
        self.criar_nova_conta_botao = QPushButton(self.Tela_2)
        self.criar_nova_conta_botao.setObjectName(u"criar_nova_conta_botao")
        self.criar_nova_conta_botao.setGeometry(QRect(80, 300, 141, 31))
        self.criar_nova_conta_botao.setStyleSheet(u"background-color: #2c3245; color: white; border-radius: 5px; border: none")
        self.line = QFrame(self.Tela_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 40, 20, 351))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.Tela_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(40, 390, 391, 16))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.Tela_2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(40, 20, 81, 16))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.ver_senha = QCheckBox(self.Tela_2)
        self.ver_senha.setObjectName(u"ver_senha")
        self.ver_senha.setGeometry(QRect(100, 240, 121, 21))
        font1 = QFont()
        font1.setFamilies([u"Tlwg Typist"])
        self.ver_senha.setFont(font1)
        self.line_2 = QFrame(self.Tela_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(420, 40, 20, 351))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.Tela_2)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(350, 20, 81, 16))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi


    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Usuario_input.setPlaceholderText(QCoreApplication.translate("Form", u"          👤 | Insira seu nome de Usuário  ", None))
        self.input_senha.setPlaceholderText(QCoreApplication.translate("Form", u"          🔒 | Insira sua senha", None))
        self.Botao_login.setText(QCoreApplication.translate("Form", u"Continuar para o Login", None))
        self.Texto_de_login.setText(QCoreApplication.translate("Form", u"Painel de Acesso", None))
        self.criar_nova_conta_botao.setText(QCoreApplication.translate("Form", u"Criar conta", None))
        self.ver_senha.setText(QCoreApplication.translate("Form", u"Ver Senha", None))
 
