
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(820, 730)
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(-20, -30, 860, 800))
        self.widget.setStyleSheet(u"background-color : #454d6b")
        self.Tela = QWidget(self.widget)
        self.Tela.setObjectName(u"Tela")
        self.Tela.setGeometry(QRect(180, 140, 501, 441))
        self.Tela.setStyleSheet(u"background-color: #373d56")
        self.Usuario_input = QLineEdit(self.Tela)
        self.Usuario_input.setObjectName(u"Usuario_input")
        self.Usuario_input.setGeometry(QRect(120, 90, 281, 51))
        self.Usuario_input.setStyleSheet(u"padding: 17px")
        self.Input_senha = QLineEdit(self.Tela)
        self.Input_senha.setObjectName(u"Input_senha")
        self.Input_senha.setGeometry(QRect(120, 150, 281, 51))
        self.Input_senha.setStyleSheet(u"padding: 17px")
        self.Input_senha.setEchoMode(QLineEdit.PasswordEchoOnEdit)
        self.continuar_botao = QPushButton(self.Tela)
        self.continuar_botao.setObjectName(u"continuar_botao")
        self.continuar_botao.setGeometry(QRect(280, 350, 141, 31))
        self.continuar_botao.setStyleSheet(u"background-color: #2c3245; border: none; border-radius: 10px")
        self.Texto_de_login = QLabel(self.Tela)
        self.Texto_de_login.setObjectName(u"Texto_de_login")
        self.Texto_de_login.setGeometry(QRect(120, 0, 261, 61))
        font = QFont()
        font.setFamilies([u"Tlwg Typo"])
        font.setPointSize(18)
        font.setItalic(True)
        self.Texto_de_login.setFont(font)
        self.voltar_botao = QPushButton(self.Tela)
        self.voltar_botao.setObjectName(u"voltar_botao")
        self.voltar_botao.setGeometry(QRect(80, 350, 141, 31))
        self.voltar_botao.setStyleSheet(u"background-color: #2c3245; border: none; border-radius: 10px")
        self.line = QFrame(self.Tela)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 20, 91, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.Tela)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(380, 20, 101, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.Tela)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 30, 16, 391))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.Tela)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(470, 30, 16, 381))
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.Tela)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(30, 410, 451, 16))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.verificar_email = QLineEdit(self.Tela)
        self.verificar_email.setObjectName(u"verificar_email")
        self.verificar_email.setGeometry(QRect(120, 210, 281, 51))
        self.verificar_email.setStyleSheet(u"padding: 17px")
        self.Ver_senha = QCheckBox(self.Tela)
        self.Ver_senha.setObjectName(u"Ver_senha")
        self.Ver_senha.setGeometry(QRect(130, 280, 121, 21))
        font1 = QFont()
        font1.setFamilies([u"Tlwg Typo"])
        font1.setItalic(True)
        self.Ver_senha.setFont(font1)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Usuario_input.setText("")
        self.Usuario_input.setPlaceholderText(QCoreApplication.translate("Form", u" 👤 | Insira seu novo nome de Usuário  ", None))
        self.Input_senha.setText("")
        self.Input_senha.setPlaceholderText(QCoreApplication.translate("Form", u"          🔒 | Insira sua senha", None))
        self.continuar_botao.setText(QCoreApplication.translate("Form", u"Continuar", None))
        self.Texto_de_login.setText(QCoreApplication.translate("Form", u"Painel de cadastro", None))
        self.voltar_botao.setText(QCoreApplication.translate("Form", u"Retornar", None))
        self.verificar_email.setText("")
        self.verificar_email.setPlaceholderText(QCoreApplication.translate("Form", u"          @ | Insira seu Email", None))
        self.Ver_senha.setText(QCoreApplication.translate("Form", u"Ver a senha", None))
    # retranslateUi
